<?php
namespace Base\Bot;
use DBModel;
class Info extends DBModel{

    public function getFieldList(){
        static $FIELD_LIST=[
            ['name'=>'id','type'=>"int",'key'=>true,'defalut'=>NULL,'null'=>false,],
            ['name'=>'bot_id','type'=>"string",'key'=>true,'defalut'=>'','null'=>true,],
            ['name'=>'bot_name','type'=>"string",'key'=>true,'defalut'=>'','null'=>true,],
            ['name'=>'nick_name','type'=>"string",'key'=>true,'defalut'=>'','null'=>true,],
            ['name'=>'bot_type','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'icon_url','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'tool_type','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'resource_type','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'resource_info','type'=>"string",'key'=>false,'defalut'=>NULL,'null'=>true,],
            ['name'=>'version','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'template_url','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'template_md5','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'template_product_url','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'classify','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'connect_type','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'protocol_type','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'bns_timeout','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'net_config','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'passport_id','type'=>"int",'key'=>true,'defalut'=>'0','null'=>true,],
            ['name'=>'developer','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'developer_home','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'summary','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'instructions','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'display_imgs','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'manual','type'=>"string",'key'=>false,'defalut'=>NULL,'null'=>true,],
            ['name'=>'bot_desc','type'=>"string",'key'=>false,'defalut'=>NULL,'null'=>true,],
            ['name'=>'language','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'query_example','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'tags','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'is_system','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'bot_url','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'deploy_type','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'smarthome_webservice_url','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'tp_cloud_url','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'biz_info','type'=>"string",'key'=>false,'defalut'=>NULL,'null'=>true,],
            ['name'=>'display_status','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'version_desc','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'oauth_id','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'reply','type'=>"string",'key'=>false,'defalut'=>NULL,'null'=>true,],
            ['name'=>'webhook','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'bot_permissions','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'source','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'is_device_debug','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'version_info','type'=>"string",'key'=>false,'defalut'=>NULL,'null'=>true,],
            ['name'=>'reason','type'=>"string",'key'=>false,'defalut'=>'','null'=>true,],
            ['name'=>'status','type'=>"int",'key'=>true,'defalut'=>'0','null'=>true,],
            ['name'=>'create_time','type'=>"string",'key'=>false,'defalut'=>'0000-00-00 00:00:00','null'=>true,],
            ['name'=>'update_time','type'=>"string",'key'=>false,'defalut'=>'0000-00-00 00:00:00','null'=>true,],
            ['name'=>'is_del','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'price','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'is_purchase','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'scene','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
            ['name'=>'pay_source','type'=>"int",'key'=>false,'defalut'=>'0','null'=>true,],
                    ];
        return $FIELD_LIST;
    }
}